---
language: python
services: docker

install:
  - pip install molecule docker

before_script:
  - cd ..
  - mv ansible-role-stepmania hadrienpatte.stepmania
  - cd hadrienpatte.stepmania

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
